name: Publish to PyPI
on: 
  push:
    branches:
      - master
jobs:
  build-and-publish:
    name: Build and publish
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@master
      - name: Set up python 3.9
        uses: actions/setup-python@v1
        with:
          python-version: 3.9
      - name: Install pypa/build
        run: >-
          python -m
          pip install
          build
          --user
      - name: Build a binary wheel and a source tarball
        run: >-
          python -m
          build
          --sdist
          --wheel
          --outdir dist/
          .
      - name: Publish distribution
        uses: pypa/gh-action-pypi-publish@master
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}
